<?php


namespace App;


use Illuminate\Contracts\View\View;
use Maatwebsite\Excel\Concerns\FromView;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\DefaultValueBinder;
use PhpOffice\PhpSpreadsheet\Cell\Cell;
use PhpOffice\PhpSpreadsheet\Cell\DataType;

class PedidosConfirmadosEnviadosExport extends DefaultValueBinder implements FromView, ShouldAutoSize, WithCustomValueBinder
{
    /**
     * @var array
     */
    private $pedidos;


    /**
     * PedidosConfirmadosEnviadosExport constructor.
     * @param array $pedidos
     */
    public function __construct(array $pedidos)
    {
        $this->pedidos = $pedidos;
    }

    public function view(): View
    {
        $pedidos = $this->pedidos;
        return view('exports.confirmaciones-amazon', compact('pedidos'));
    }

    public function bindValue(Cell $cell, $value)
    {
        if (is_numeric($value)) {
            $cell->setValueExplicit($value, DataType::TYPE_STRING);
            return true;
        }
        return parent::bindValue($cell, $value); // TODO: Change the autogenerated stub
    }
}
